name: Cypress Test in custom container
on: [push]
jobs:
  cypress-test:
    runs-on: ubuntu-20.04
    name: Cypress Tests on docker container
    # Cypress Docker image with Chrome v107 pre-installed
    container: cypress/browsers:node18.12.0-chrome107
    
    
    steps:
      - uses: actions/checkout@v2
      - run: cypress run

    
