name: Cypress Test in custom container
on: [push]
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    name: Cypress Tests on docker container
    # Cypress Docker image with Chrome v107 pre-installed
    container: cypress/browsers:node18.12.0-chrome107
    
    
    steps:
      - uses: actions/checkout@v2
      

        - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome

    
