name: Cypress Cloud Tests
on: [push]
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2


      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install


      - name: Start LT Tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v1
        id: tunnel
       
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "testTunnel"
      - run: npm run lambdatest-cypress run
      

      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
