name: Cypress Cloud Tests
on: [push]
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2


      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install


      - name: Run Cypress Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run lambdatest-cypress run --username anshita.bhasin --key yxu3wRJAzjY2rpgWjla3S5kBqwWTryAlfZIWNbdSGURPoXyoxR
          browser: chrome


   
