name: Cypress Tests
on: [push]
jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Run Cypress Test
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          browser: chrome

      - name: Run Cypress Test on cloud platform
        uses: actions/setup-node@v3
        with:
        - run: npm ci
        - run: npm install lambdatest-cypress-cli
        - run: lambdatest-cypress init
        - run: lambdatest-cypress run

